name: publish to github.io
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@v2.0.0
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: cvSoldier/cvSoldier.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: git config --global --add safe.directory "*" && cd docs && npm i && npm run build
        BUILD_DIR: docs/.vuepress/dist/
        COMMIT_MESSAGE:  Auto deploy by the Vuepress-deploy
